/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ortus.boxlang.lsp;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.lsp4j.DocumentSymbol;
import org.eclipse.lsp4j.Position;
import org.eclipse.lsp4j.Range;
import org.eclipse.lsp4j.SymbolInformation;
import org.eclipse.lsp4j.SymbolKind;
import org.eclipse.lsp4j.jsonrpc.messages.Either;

import ortus.boxlang.compiler.ast.BoxClass;
import ortus.boxlang.compiler.ast.BoxInterface;
import ortus.boxlang.compiler.ast.BoxNode;
import ortus.boxlang.compiler.ast.expression.BoxStringLiteral;
import ortus.boxlang.compiler.ast.statement.BoxAnnotation;
import ortus.boxlang.compiler.ast.statement.BoxArgumentDeclaration;
import ortus.boxlang.compiler.ast.statement.BoxFunctionDeclaration;
import ortus.boxlang.compiler.ast.statement.BoxProperty;
import ortus.boxlang.compiler.ast.visitor.VoidBoxVisitor;

public class DocumentSymbolBoxNodeVisitor extends VoidBoxVisitor {

	private List<Either<SymbolInformation, DocumentSymbol>>	documentSymbols	= new ArrayList<Either<SymbolInformation, DocumentSymbol>>();
	private List<DocumentSymbol>							symbolStack		= new ArrayList<DocumentSymbol>();
	private Path											filePath;

	public List<Either<SymbolInformation, DocumentSymbol>> getDocumentSymbols() {
		return documentSymbols;
	}

	public void setFilePath( Path filePath ) {
		this.filePath = filePath;
	}

	public void visit( BoxClass node ) {

		DocumentSymbol classSymbol = new DocumentSymbol();
		// find the class name
		classSymbol.setName( getClassName() );
		classSymbol.setKind( SymbolKind.Class );
		Range range = getRange( node );
		classSymbol.setRange( range );
		classSymbol.setSelectionRange( range );

		trackSymbol( classSymbol );
		classSymbol.setChildren( new ArrayList<DocumentSymbol>() );
		this.symbolStack.add( classSymbol );

		visitChildren( node );

		// Sort children: properties first, then constructor, then methods
		sortClassChildren( classSymbol );

		this.symbolStack.remove( symbolStack.size() - 1 );
	}

	public void visit( BoxInterface node ) {

		DocumentSymbol interfaceSymbol = new DocumentSymbol();
		// find the interface name
		interfaceSymbol.setName( getClassName() );
		interfaceSymbol.setKind( SymbolKind.Interface );
		Range range = getRange( node );
		interfaceSymbol.setRange( range );
		interfaceSymbol.setSelectionRange( range );

		trackSymbol( interfaceSymbol );
		interfaceSymbol.setChildren( new ArrayList<DocumentSymbol>() );
		this.symbolStack.add( interfaceSymbol );

		visitChildren( node );

		// Sort children: properties first, then methods
		sortClassChildren( interfaceSymbol );

		this.symbolStack.remove( symbolStack.size() - 1 );
	}

	public void visit( BoxProperty node ) {
		if ( !inClassOrInterface() ) {
			visitChildren( node );
			return;
		}

		DocumentSymbol	property		= new DocumentSymbol();
		BoxAnnotation	nameAnnotation	= node.getAllAnnotations()
		    .stream()
		    .filter( annotation -> annotation.getKey().getValue().equalsIgnoreCase( "name" ) )
		    .findFirst()
		    .orElseGet( () -> node.getAllAnnotations().get( 0 ) );

		if ( nameAnnotation.getValue() == null ) {
			property.setName( nameAnnotation.getKey().getValue() );
		} else if ( nameAnnotation.getValue() instanceof BoxStringLiteral bsl ) {
			property.setName( bsl.getValue() );
		} else {
			property.setName( nameAnnotation.getValue().toString() );
		}
		property.setKind( SymbolKind.Property );

		// Extract type hint for detail
		String typeHint = getPropertyTypeHint( node );
		if ( typeHint != null && !typeHint.isEmpty() ) {
			property.setDetail( typeHint );
		}

		Range r = getRange( node );
		property.setRange( r );
		property.setSelectionRange( r );

		trackSymbol( property );
		visitChildren( node );
	}

	public void visit( BoxFunctionDeclaration node ) {
		DocumentSymbol functionSymbol = new DocumentSymbol();

		functionSymbol.setKind( SymbolKind.Function );

		if ( this.inClassOrInterface() ) {
			// Check if this is a constructor (init method)
			if ( node.getName().equalsIgnoreCase( "init" ) ) {
				functionSymbol.setKind( SymbolKind.Constructor );
			} else {
				functionSymbol.setKind( SymbolKind.Method );
			}
		}

		functionSymbol.setName( node.getName() );

		// Build detail string with return type and parameter summary
		String detail = buildFunctionDetail( node );
		functionSymbol.setDetail( detail );

		Range range = getRange( node );
		functionSymbol.setRange( range );
		functionSymbol.setSelectionRange( range );

		trackSymbol( functionSymbol );

		// Support nested functions
		functionSymbol.setChildren( new ArrayList<DocumentSymbol>() );
		this.symbolStack.add( functionSymbol );

		visitChildren( node );

		this.symbolStack.remove( symbolStack.size() - 1 );
	}

	// public void visit( BoxAssignment node ) {
	// if ( ! ( node.getLeft() instanceof BoxIdentifier ) ) {
	// visitChildren( node );
	// return;
	// }
	// BoxIdentifier id = ( BoxIdentifier ) node.getLeft();
	// DocumentSymbol assignmentSymbol = new DocumentSymbol();

	// assignmentSymbol.setKind( SymbolKind.Variable );

	// assignmentSymbol.setName( id.getName() );
	// Range range = getRange( node );
	// assignmentSymbol.setRange( range );
	// assignmentSymbol.setSelectionRange( range );

	// trackSymbol( assignmentSymbol );
	// visitChildren( node );
	// }

	private void trackSymbol( DocumentSymbol symbol ) {
		if ( symbolStack.size() > 0 ) {
			DocumentSymbol parent = symbolStack.get( symbolStack.size() - 1 );
			if ( parent.getChildren() != null ) {
				parent.getChildren().add( symbol );
			}
			return;
		}

		documentSymbols.add( Either.forRight( symbol ) );
	}

	private boolean inClassOrInterface() {
		if ( symbolStack.isEmpty() ) {
			return false;
		}
		SymbolKind kind = symbolStack.get( symbolStack.size() - 1 ).getKind();
		return kind == SymbolKind.Class || kind == SymbolKind.Interface;
	}

	/**
	 * Extract type hint from property annotations.
	 */
	private String getPropertyTypeHint( BoxProperty node ) {
		return node.getAllAnnotations()
		    .stream()
		    .filter( annotation -> annotation.getKey().getValue().equalsIgnoreCase( "type" ) )
		    .findFirst()
		    .map( annotation -> {
			    if ( annotation.getValue() instanceof BoxStringLiteral bsl ) {
				    return bsl.getValue();
			    } else if ( annotation.getValue() != null ) {
				    return annotation.getValue().toString();
			    }
			    return null;
		    } )
		    .orElse( null );
	}

	/**
	 * Build detail string for a function including return type and parameter summary.
	 */
	private String buildFunctionDetail( BoxFunctionDeclaration node ) {
		StringBuilder detail = new StringBuilder();

		// Add return type
		if ( node.getType() != null ) {
			detail.append( node.getType().toString() );
		} else {
			detail.append( "any" );
		}

		// Add parameter summary
		List<BoxArgumentDeclaration> args = node.getArgs();
		if ( args != null && !args.isEmpty() ) {
			detail.append( " (" );
			detail.append( args.stream()
			    .map( arg -> {
				    StringBuilder paramStr = new StringBuilder();
				    if ( arg.getType() != null ) {
					    paramStr.append( arg.getType().toString() ).append( " " );
				    }
				    paramStr.append( arg.getName() );
				    return paramStr.toString();
			    } )
			    .collect( Collectors.joining( ", " ) ) );
			detail.append( ")" );
		}

		return detail.toString();
	}

	/**
	 * Sort class/interface children: properties first, then constructor, then methods.
	 */
	private void sortClassChildren( DocumentSymbol classSymbol ) {
		if ( classSymbol.getChildren() == null || classSymbol.getChildren().isEmpty() ) {
			return;
		}

		classSymbol.getChildren().sort( Comparator
		    .comparingInt( ( DocumentSymbol s ) -> getSymbolSortOrder( s.getKind() ) )
		    .thenComparing( DocumentSymbol::getName, String.CASE_INSENSITIVE_ORDER ) );
	}

	/**
	 * Get sort order for a symbol kind (lower = first).
	 */
	private int getSymbolSortOrder( SymbolKind kind ) {
		return switch ( kind ) {
			case Property -> 0;
			case Constructor -> 1;
			case Method -> 2;
			case Function -> 3;
			default -> 4;
		};
	}

	private Range getRange( BoxNode node ) {
		ortus.boxlang.compiler.ast.Position pos = node.getPosition();
		return new Range(
		    new Position( pos.getStart().getLine() - 1, pos.getStart().getColumn() ),
		    new Position( pos.getEnd().getLine() - 1, pos.getEnd().getColumn() ) );
	}

	private String getClassName() {
		if ( this.filePath == null ) {
			return "Class";
		}

		String path = this.filePath.getFileName().toString();

		if ( path.indexOf( "." ) > 0 ) {
			return path.substring( 0, path.lastIndexOf( "." ) );
		} else {
			return path;
		}
	}

	private void visitChildren( BoxNode node ) {
		for ( BoxNode child : node.getChildren() ) {
			child.accept( this );
		}
	}
}
