name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  # Format PR
  format_check:
    name: Checks Source Code Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script format:check

      - name: Verify Code Formatting
        run: ./gradlew spotlessCheck
